# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8Z4FoiY8mmEJCDZJZNOK0SQXaZ1E3k1
"""

import numpy as np

def getBondPrice(y, face, couponRate, m, ppy=1):
    YTM = y / ppy
    coupon_payment = face * couponRate / ppy
    t = np.arange(1, m * ppy + 1)
    pv_coupons = coupon_payment / ((1 + YTM) ** t)
    pv_face = face / ((1 + YTM) ** (m * ppy))
    return np.sum(pv_coupons) + pv_face

y = 0.03
face = 2000000
couponRate = 0.04
m = 10

price_ppy_1 = getBondPrice(y, face, couponRate, m, ppy=1)
print("Bond Price with ppy=1:", price_ppy_1)

price_ppy_2 = getBondPrice(y, face, couponRate, m, ppy=2)
print("Bond Price with ppy=2:", price_ppy_2)

price_ppy_default = getBondPrice(y, face, couponRate, m)
print("Bond Price with default ppy (which is 1):", price_ppy_default)