# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8Z4FoiY8mmEJCDZJZNOK0SQXaZ1E3k1
"""

import numpy as np

def getBondDuration(y, face, couponRate, m, ppy):
    coupon = (couponRate * face) / ppy
    t = np.arange(1, m * ppy + 1) / ppy
    discount_factors = (1 + y / ppy) ** (-ppy * t)
    pv_coupons = coupon * discount_factors
    pv_face = face * discount_factors[-1]
    pv_total = np.sum(pv_coupons) + pv_face
    weighted_time = np.sum(t * pv_coupons) + t[-1] * pv_face
    return weighted_time / pv_total

y = 0.03
face = 2000000
couponRate = 0.04
m = 10

print(getBondDuration(y, face, couponRate, m, 1))
print(getBondDuration(y, face, couponRate, m, 2))