# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8Z4FoiY8mmEJCDZJZNOK0SQXaZ1E3k1
"""

import numpy as np

def FizzBuzz(start, finish):
    numvec = np.arange(start, finish + 1)
    objvec = numvec.astype(object)

    objvec[(numvec % 3 == 0) & (numvec % 5 == 0)] = 'fizzbuzz'
    objvec[(numvec % 3 == 0) & (numvec % 5 != 0)] = 'fizz'
    objvec[(numvec % 5 == 0) & (numvec % 3 != 0)] = 'buzz'

    return objvec

result = FizzBuzz(40, 45)
for x in result:
    print(x)