# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8Z4FoiY8mmEJCDZJZNOK0SQXaZ1E3k1
"""

def WhoAmI():
    return('zw3020')